name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # <-- allow pushing commits back to repo
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false   # important for custom push
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: Livhuwani9308
